version: '3.3'

services:
  nginx :
        build:
          context: .
          dockerfile: docker/Nginx.Dockerfile
        ports:
          - 8088:80
        links:
          - fpm
        volumes:
          - ./ :/var/www/laravel-docker
        networks:
          - internal
  fpm:
    build:
        context: .
        dockerfile: docker/Fpm.Dockerfile
    volumes:
       - ./:/var/www/laravel-docker
    links:
      - mysql
    environment:
      XDEBUG_CONFIG: "remote_host=host.docker.internal
      remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
    networks:
      - internal

  mysql:
       image: mysql:5.7
       ports:
       - 33062:3306
       environment:
         - MYSQL_ROOT_PASSWORD=root
         - MYSQL_DATABASE=bot
         - MYSQL_USER=root
         - MYSQL_PASSWORD=root
networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet : 192.168.220.0/28


