version: '3.3'

services:
  nginx :
        build:
          context: .
          dockerfile: docker/Nginx.Dockerfile
        ports:
          - 8088:80
        links:
          - fpm
        volumes:
          - ./ :/var/www/laravel-docker
  fpm:
    build:
        context: .
        dockerfile: docker/Fpm.Dockerfile
    volumes:
       - ./:/var/www/laravel-docker
    links:
      - mysql
      - redis
  mysql:
       image: mysql:5.7
       ports:
       - 33062:3306
       environment:
         - MYSQL_ROOT_PASSWORD=root
         - MYSQL_DATABASE=bot
         - MYSQL_USER=root
         - MYSQL_PASSWORD=root

  redis:
    image: "redis:alpine"
    command: redis-server --requirepass test
    ports:
      - 6379:6379
    volumes:
      - ./docker/conf/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master


